name: First Workflow

# Trigger the workflow on any push to the repository
on: push

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print a welcome message
        run: echo "Hello, DevOps"